name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - preprod
          - prod

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Lowercase Image Name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV

      - name: Set Environment Variables
        run: |
          if [ "${{ inputs.environment }}" == "prod" ]; then
            echo "TARGET_IP=${{ secrets.PROD_IP }}" >> $GITHUB_ENV
            echo "SSH_PRIVATE_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.PROD_SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "BASIC_SECRET=${{ secrets.PROD_BASIC_SECRET }}" >> $GITHUB_ENV
            echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_PROD_URL }}" >> $GITHUB_ENV
          else
            echo "TARGET_IP=${{ secrets.PREPROD_IP }}" >> $GITHUB_ENV
            echo "SSH_PRIVATE_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.PREPROD_SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "BASIC_SECRET=${{ secrets.PREPROD_BASIC_SECRET }}" >> $GITHUB_ENV
            echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_PREPROD_URL }}" >> $GITHUB_ENV
          fi

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.TARGET_IP }}
          username: github
          key: ${{ env.SSH_PRIVATE_KEY }}
          envs: BASIC_SECRET, IMAGE_NAME, GITHUB_ACTOR
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
            docker pull ghcr.io/$IMAGE_NAME:latest
            docker stop taskflow-backend || true
            docker rm taskflow-backend || true
            docker run -d \
              --restart always \
              -p 4000:4000 \
              -e BASIC_SECRET=$BASIC_SECRET \
              --name taskflow-backend \
              ghcr.io/$IMAGE_NAME:latest

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_WEBHOOK: ${{ env.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: taskflow-backend-deploy
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "Deploy finished with status: ${{ job.status }}"
          SLACK_TITLE: Deploy Status
          SLACK_USERNAME: GitHub Actions