name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - preprod
          - prod

jobs:
  deploy:
    runs-on: self-hosted
    env:
      REGISTRY: ghcr.io
    steps:
      - name: Lowercase Image Name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV

      - name: Set target ip
        run: |
          if [ "${{ inputs.environment }}" == "prod" ]; then
            echo "SSH_PRIVATE_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.PROD_SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "TARGET_IP=${{ secrets.PROD_IP }}" >> $GITHUB_ENV
          else
            echo "SSH_PRIVATE_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.PREPROD_SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "TARGET_IP=${{ secrets.PREPROD_IP }}" >> $GITHUB_ENV
          fi

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.TARGET_IP }}
          username: github
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ env.IMAGE_NAME }}:latest
            docker stop taskflow-backend || true
            docker rm taskflow-backend || true
            docker run -d --restart always -p 4000:4000 --name taskflow-backend ghcr.io/${{ env.IMAGE_NAME }}:latest
